---
- name: fail on incorrectly set frequency
  fail:
    msg: "Incorrect value for enrollment_report_frequency: {{ enrollment_report_frequency }} (must be 'monthly' or 'weekly')."
  when: 'enrollment_report_frequency not in ["monthly", "weekly"]'

- name: set start date (monthly run)
  set_fact:
    _enrollment_report_start_date: "{{ lookup('pipe', 'date +\"%Y-%m-%d\" -d \"today - 1 month\"') }}"
    _enrollment_report_start_datetime: "{{ lookup('pipe', 'date +\"%Y-%m-%d %H:%M:%S\" -d \"today - 1 month 00:00:00\"') }}"
  when: enrollment_report_frequency == "monthly"

- name: set start date (weekly run)
  set_fact:
    _enrollment_report_start_date: "{{ lookup('pipe', 'date +\"%Y-%m-%d\" -d \"today - 1 week\"') }}"
    _enrollment_report_start_datetime: "{{ lookup('pipe', 'date +\"%Y-%m-%d %H:%M:%S\" -d \"today - 1 week 00:00:00\"') }}"
  when: enrollment_report_frequency == "weekly"

- name: set end date
  set_fact:
    _enrollment_report_end_date: "{{ lookup('pipe', 'date +\"%Y-%m-%d \" -d \"yesterday\"') }}"
    _enrollment_report_end_datetime: "{{ lookup('pipe', 'date +\"%Y-%m-%d %H:%M:%S\" -d \"yesterday 23:59:59\"') }}"

- name: define facts for TSV output
  set_fact:
    _enrollment_report_delimiter: '\t'
    _enrollment_report_file_suffix: '.tsv'
  when: enrollment_report_format == 'tsv'

- name: define facts for CSV output
  set_fact:
    _enrollment_report_delimiter: ','
    _enrollment_report_file_suffix: '.csv'
  when: enrollment_report_format == 'csv'

- name: create temporary directory to contain reports
  tempfile:
    state: directory
  register: _enrollment_report_directory

- name: set output file names
  set_fact:
    _enrollment_report_filename: "enrollment_report_{{ _enrollment_report_start_date }}_{{ _enrollment_report_end_date }}{{ _enrollment_report_file_suffix }}"
    _enrollment_report_pass_filename: "pass_report_{{ _enrollment_report_start_date }}_{{ _enrollment_report_end_date }}{{ _enrollment_report_file_suffix }}"
    _enrollment_report_percent_filename: "percent_report_{{ _enrollment_report_start_date }}_{{ _enrollment_report_end_date }}{{ _enrollment_report_file_suffix }}"
    _enrollment_report_lab_filename: "lab_report_{{ _enrollment_report_start_date }}_{{ _enrollment_report_end_date }}{{ _enrollment_report_file_suffix }}"
    _enrollment_report_historical_filename: "enrollment_report_historical_{{ _enrollment_report_end_date }}{{ _enrollment_report_file_suffix }}"
    _enrollment_report_pass_historical_filename: "pass_report_historical_{{ _enrollment_report_end_date }}{{ _enrollment_report_file_suffix }}"
    _enrollment_report_percent_historical_filename: "percent_report_historical_{{ _enrollment_report_end_date }}{{ _enrollment_report_file_suffix }}"
    _enrollment_report_lab_historical_filename: "lab_report_historical_{{ _enrollment_report_end_date }}{{ _enrollment_report_file_suffix }}"
    _enrollment_report_lab_historical_by_learner_filename: "lab_report_historical_by_learner_{{ _enrollment_report_end_date }}{{ _enrollment_report_file_suffix }}"

- name: set output file paths
  set_fact:
    _enrollment_report_outfile: "{{ _enrollment_report_directory.path }}/{{ _enrollment_report_filename }}"
    _enrollment_report_pass_outfile: "{{ _enrollment_report_directory.path }}/{{ _enrollment_report_pass_filename }}"
    _enrollment_report_percent_outfile: "{{ _enrollment_report_directory.path }}/{{ _enrollment_report_percent_filename }}"
    _enrollment_report_lab_outfile: "{{ _enrollment_report_directory.path }}/{{ _enrollment_report_lab_filename }}"
    _enrollment_report_historical_outfile: "{{ _enrollment_report_directory.path }}/{{ _enrollment_report_historical_filename }}"
    _enrollment_report_pass_historical_outfile: "{{ _enrollment_report_directory.path }}/{{ _enrollment_report_pass_historical_filename }}"
    _enrollment_report_percent_historical_outfile: "{{ _enrollment_report_directory.path }}/{{ _enrollment_report_percent_historical_filename }}"
    _enrollment_report_lab_historical_outfile: "{{ _enrollment_report_directory.path }}/{{ _enrollment_report_lab_historical_filename }}"
    _enrollment_report_lab_historical_by_learner_outfile: "{{ _enrollment_report_directory.path }}/{{ _enrollment_report_lab_historical_by_learner_filename }}"

- name: create tempfile for enrollment report SQL
  tempfile:
    state: file
    suffix: .sql
  register: _enrollment_report_sql

- name: populate enrollment report SQL
  template:
    dest: "{{ _enrollment_report_sql.path }}"
    src: enrollment-report.sql.j2
    mode: 0644

- name: create tempfile for historical enrollment report SQL
  tempfile:
    state: file
    suffix: .sql
  register: _enrollment_report_historical_sql

- name: populate historical enrollment report SQL
  template:
    dest: "{{ _enrollment_report_historical_sql.path }}"
    src: enrollment-report-historical.sql.j2
    mode: 0644

- name: create tempfile for "pass" report SQL
  tempfile:
    state: file
    suffix: .sql
  register: _enrollment_report_pass_sql

- name: populate "pass" report SQL
  template:
    dest: "{{ _enrollment_report_pass_sql.path }}"
    src: grade-report-pass.sql.j2
    mode: 0644

- name: create tempfile for historical "pass" report SQL
  tempfile:
    state: file
    suffix: .sql
  register: _enrollment_report_pass_historical_sql

- name: populate historical "pass" report SQL
  template:
    dest: "{{ _enrollment_report_pass_historical_sql.path }}"
    src: grade-report-pass-historical.sql.j2
    mode: 0644

- name: create tempfile for "percent" report SQL
  tempfile:
    state: file
    suffix: .sql
  register: _enrollment_report_percent_sql

- name: populate "percent" report SQL
  template:
    dest: "{{ _enrollment_report_percent_sql.path }}"
    src: grade-report-percent.sql.j2
    mode: 0644

- name: 'create tempfile for historical "percent" report SQL'
  tempfile:
    state: file
    suffix: .sql
  register: _enrollment_report_percent_historical_sql

- name: 'populate historical "percent" report SQL'
  template:
    dest: "{{ _enrollment_report_percent_historical_sql.path }}"
    src: grade-report-percent-historical.sql.j2
    mode: 0644

- name: create tempfile for "lab" report SQL
  tempfile:
    state: file
    suffix: .sql
  register: _enrollment_report_lab_sql

- name: populate "lab" report SQL
  template:
    dest: "{{ _enrollment_report_lab_sql.path }}"
    src: lab-report.sql.j2
    mode: 0644

- name: create tempfile for "historical lab" report SQL
  tempfile:
    state: file
    suffix: .sql
  register: _enrollment_report_lab_historical_sql

- name: populate "historical lab" report SQL
  template:
    dest: "{{ _enrollment_report_lab_historical_sql.path }}"
    src: lab-report-historical.sql.j2
    mode: 0644

- name: create tempfile for "historical lab by learner" report SQL
  tempfile:
    state: file
    suffix: .sql
  register: _enrollment_report_lab_historical_by_learner_sql

- name: populate "historical_by lab by learner" report SQL
  template:
    dest: "{{ _enrollment_report_lab_historical_by_learner_sql.path }}"
    src: lab-report-historical-by-learner.sql.j2
    mode: 0644

- name: execute scripts
  become: true
  become_user: root
  shell: "mysql --batch {{ enrollment_report_database }} < {{ item.in }} > {{ item.out }}"  # noqa 301
  with_items:
    - in: "{{ _enrollment_report_sql.path }}"
      out: "{{ _enrollment_report_outfile }}"
    - in: "{{ _enrollment_report_pass_sql.path }}"
      out: "{{ _enrollment_report_pass_outfile }}"
    - in: "{{ _enrollment_report_percent_sql.path }}"
      out: "{{ _enrollment_report_percent_outfile }}"
    - in: "{{ _enrollment_report_lab_sql.path }}"
      out: "{{ _enrollment_report_lab_outfile }}"
    - in: "{{ _enrollment_report_historical_sql.path }}"
      out: "{{ _enrollment_report_historical_outfile }}"
    - in: "{{ _enrollment_report_pass_historical_sql.path }}"
      out: "{{ _enrollment_report_pass_historical_outfile }}"
    - in: "{{ _enrollment_report_percent_historical_sql.path }}"
      out: "{{ _enrollment_report_percent_historical_outfile }}"
    - in: "{{ _enrollment_report_lab_historical_sql.path }}"
      out: "{{ _enrollment_report_lab_historical_outfile }}"
    - in: "{{ _enrollment_report_lab_historical_by_learner_sql.path }}"
      out: "{{ _enrollment_report_lab_historical_by_learner_outfile }}"

- name: ensure output directory exists
  file:
    state: directory
    mode: '0750'
    name: "{{ enrollment_report_path }}"

- name: fetch enrollment reports
  synchronize:
    mode: pull
    dest: "{{ enrollment_report_path }}/"
    src: "{{ _enrollment_report_directory.path }}/"
    use_ssh_args: true

- name: create attachment list
  set_fact:
    _enrollment_report_attachments:
      - "{{ enrollment_report_path }}/{{ _enrollment_report_filename }}"
      - "{{ enrollment_report_path }}/{{ _enrollment_report_pass_filename }}"
      - "{{ enrollment_report_path }}/{{ _enrollment_report_percent_filename }}"
      - "{{ enrollment_report_path }}/{{ _enrollment_report_lab_filename }}"
      - "{{ enrollment_report_path }}/{{ _enrollment_report_historical_filename }}"
      - "{{ enrollment_report_path }}/{{ _enrollment_report_pass_historical_filename }}"
      - "{{ enrollment_report_path }}/{{ _enrollment_report_percent_historical_filename }}"
      - "{{ enrollment_report_path }}/{{ _enrollment_report_lab_historical_filename }}"
      - "{{ enrollment_report_path }}/{{ _enrollment_report_lab_historical_by_learner_filename }}"
  when: enrollment_report_mail_enable

- name: send out enrollment reports
  mail:
    subject: "Enrollment reports for {{ enrollment_report_hostname }} ({{ _enrollment_report_start_date }} - {{ _enrollment_report_end_date }})"
    from: "{{ enrollment_report_mail_from }}"
    to: "{{ enrollment_report_mail_to }}"
    cc: "{{ enrollment_report_mail_cc }}"
    attach: "{{ _enrollment_report_attachments }}"
    charset: utf8
    host: "{{ enrollment_report_mail_host | default(omit) }}"
    port: "{{ enrollment_report_mail_port | default(omit) }}"
    username: "{{ enrollment_report_mail_username | default(omit) }}"
    password: "{{ enrollment_report_mail_password | default(omit) }}"
    secure: "{{ enrollment_report_mail_secure | default(omit) }}"
  delegate_to: localhost
  when: enrollment_report_mail_enable

- name: delete enrollment report directory
  become: true
  become_user: root
  file:
    path: "{{ _enrollment_report_directory.path }}"
    state: absent

- name: delete SQL files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ _enrollment_report_sql.path }}"
    - "{{ _enrollment_report_pass_sql.path }}"
    - "{{ _enrollment_report_percent_sql.path }}"
    - "{{ _enrollment_report_lab_sql.path }}"
    - "{{ _enrollment_report_historical_sql.path }}"
    - "{{ _enrollment_report_pass_historical_sql.path }}"
    - "{{ _enrollment_report_percent_historical_sql.path }}"
    - "{{ _enrollment_report_lab_historical_sql.path }}"
    - "{{ _enrollment_report_lab_historical_by_learner_sql.path }}"
